import colors from 'open-color'

export default {
  '@red-6': colors.red[6],
  '@blue-6': colors.blue[6],
  '@cyan-6': colors.cyan[6],
  '@lime-6': colors.lime[6],
  '@pink-6': colors.pink[6],
  '@green-6': colors.green[6],
  '@orange-6': colors.orange[6],
  '@yellow-6': colors.yellow[6],
  '@primary-color': colors.indigo[6],
  '@font-size-sm': '14px',
  '@font-size-base': '16px',
  '@btn-font-size-sm': '14px',
  '@btn-height-sm': '32px',
  '@btn-height-base': '42px',
  '@btn-height-lg': '52px',
  '@radio-size': '18px',
  '@checkbox-size': '18px',
  '@badge-status-size': '11px',
  '@input-height-sm': '32px',
  '@input-height-base': '40px',
  '@input-height-lg': '48px',
  '@input-padding-vertical-sm': '4px',
  '@input-padding-vertical-base': '8px',
  '@input-padding-vertical-lg': '12px',
  '@input-padding-horizontal-lg': '12px',
  '@form-item-margin-bottom': '20px',
  '@pagination-item-size-sm': '32px',
  '@pagination-item-size': '40px',
  '@dropdown-line-height': '32px',
  '@select-dropdown-height': '46px',
  '@dropdown-vertical-padding': '7px',
}
